/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jsdl_jsdl */

#ifndef _Included_com_jsdl_jsdl
#define _Included_com_jsdl_jsdl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jsdl_jsdl_INIT
#define com_jsdl_jsdl_INIT 1073L
/*
 * Class:     com_jsdl_jsdl
 * Method:    Init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jsdl_jsdl_Init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jsdl_jsdl
 * Method:    CreateWindow
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_jsdl_jsdl_CreateWindow
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_jsdl_jsdl
 * Method:    Delay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jsdl_jsdl_Delay
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jsdl_jsdl
 * Method:    Quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jsdl_jsdl_Quit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
